### PR TITLE
Mrc abstracted

### PR DESCRIPTION
**Pull request by pookmish**

### CODE REVIEW

**Comment by boznik** [comment]
think this needs updated:

https://github.com/SU-HSDO/hs_events/blob/mrc-abstracted/composer.json#L5

**Comment by pookmish** [comment]
fixed that homepage part

**Comment by boznik** [comment]
fixed the repo in package.json, but composer is still complaining:
[Composer\Downloader\TransportException]                                                                   
  The "https://api.github.com/repos/SU-SWS/hs_events" file could not be downloaded (HTTP/1.1 404 Not Found) 
nm, bad repository entry in composer.json

**Comment by boznik** [comment]
maybe we should add the dropzone library in stanford_media

**Pull request merged**
